name: Run Test Suite on PR or push to master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.207
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: |
          dotnet test VRDR.Tests/DeathRecord.Tests.csproj
          dotnet run -p VRDR.CLI json2json VRDR.CLI/1.json
          dotnet run -p VRDR.CLI xml2xml VRDR.CLI/1.xml
          dotnet run -p VRDR.CLI description VRDR.CLI/1.xml
          dotnet run -p VRDR.CLI description VRDR.CLI/1.json
          dotnet run -p VRDR.CLI roundtrip-ije VRDR.CLI/1.xml
          dotnet run -p VRDR.CLI roundtrip-ije VRDR.CLI/1.json
          dotnet run -p VRDR.CLI roundtrip-all VRDR.CLI/1.xml
          dotnet run -p VRDR.CLI roundtrip-all VRDR.CLI/1.json
          ./VRDR.Tests/test_translation_service.sh
